/** 12 régions administratives du Maroc (2015) — villes principales par région. */
export const MOROCCO_REGIONS = [
  "Tanger-Tétouan-Al Hoceïma",
  "Oriental",
  "Fès-Meknès",
  "Rabat-Salé-Kénitra",
  "Béni Mellal-Khénifra",
  "Casablanca-Settat",
  "Marrakech-Safi",
  "Drâa-Tafilalet",
  "Souss-Massa",
  "Guelmim-Oued Noun",
  "Laâyoune-Sakia El Hamra",
  "Dakhla-Oued Ed-Dahab",
  "Autres communes",
] as const;

export type MoroccoRegion = (typeof MOROCCO_REGIONS)[number];

const normalizeKey = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();

/** Villes et communes → région administrative. */
const CITY_TO_REGION: Record<string, MoroccoRegion> = {
  tanger: "Tanger-Tétouan-Al Hoceïma",
  tetouan: "Tanger-Tétouan-Al Hoceïma",
  "al hoceima": "Tanger-Tétouan-Al Hoceïma",
  larache: "Tanger-Tétouan-Al Hoceïma",
  chefchaouen: "Tanger-Tétouan-Al Hoceïma",
  ouazzane: "Tanger-Tétouan-Al Hoceïma",
  mdik: "Tanger-Tétouan-Al Hoceïma",
  fnideq: "Tanger-Tétouan-Al Hoceïma",
  martil: "Tanger-Tétouan-Al Hoceïma",
  asilah: "Tanger-Tétouan-Al Hoceïma",
  "ksar el kebir": "Tanger-Tétouan-Al Hoceïma",
  "m diq": "Tanger-Tétouan-Al Hoceïma",

  oujda: "Oriental",
  nador: "Oriental",
  berkane: "Oriental",
  taourirt: "Oriental",
  jerada: "Oriental",
  figuig: "Oriental",
  guercif: "Oriental",
  driouch: "Oriental",
  ahfir: "Oriental",
  saidia: "Oriental",
  "beni drar": "Oriental",

  fes: "Fès-Meknès",
  meknes: "Fès-Meknès",
  meknès: "Fès-Meknès",
  taza: "Fès-Meknès",
  sefrou: "Fès-Meknès",
  ifrane: "Fès-Meknès",
  "el hajeb": "Fès-Meknès",
  azrou: "Fès-Meknès",
  "moulay yacoub": "Fès-Meknès",
  "sidi kacem": "Fès-Meknès",
  "sidi slimane": "Fès-Meknès",

  rabat: "Rabat-Salé-Kénitra",
  sale: "Rabat-Salé-Kénitra",
  salé: "Rabat-Salé-Kénitra",
  kenitra: "Rabat-Salé-Kénitra",
  kénitra: "Rabat-Salé-Kénitra",
  temara: "Rabat-Salé-Kénitra",
  skhirate: "Rabat-Salé-Kénitra",
  skhirat: "Rabat-Salé-Kénitra",
  khemisset: "Rabat-Salé-Kénitra",
  khémisset: "Rabat-Salé-Kénitra",
  bouznika: "Rabat-Salé-Kénitra",
  "sidi yahya": "Rabat-Salé-Kénitra",
  "sidi allal el bahraoui": "Rabat-Salé-Kénitra",

  "beni mellal": "Béni Mellal-Khénifra",
  "béni mellal": "Béni Mellal-Khénifra",
  khenifra: "Béni Mellal-Khénifra",
  khénifra: "Béni Mellal-Khénifra",
  khouribga: "Béni Mellal-Khénifra",
  "fquih ben salah": "Béni Mellal-Khénifra",
  azilal: "Béni Mellal-Khénifra",
  "kasba tadla": "Béni Mellal-Khénifra",
  "oued zem": "Béni Mellal-Khénifra",

  casablanca: "Casablanca-Settat",
  mohammedia: "Casablanca-Settat",
  settat: "Casablanca-Settat",
  berrechid: "Casablanca-Settat",
  "el jadida": "Casablanca-Settat",
  bouskoura: "Casablanca-Settat",
  nouaceur: "Casablanca-Settat",
  mediouna: "Casablanca-Settat",
  "dar bouazza": "Casablanca-Settat",
  azemmour: "Casablanca-Settat",
  "had soualem": "Casablanca-Settat",
  "sidi rahal": "Casablanca-Settat",
  "el mansouria": "Casablanca-Settat",

  marrakech: "Marrakech-Safi",
  safi: "Marrakech-Safi",
  essaouira: "Marrakech-Safi",
  "el kelaa des sraghna": "Marrakech-Safi",
  youssoufia: "Marrakech-Safi",
  chichaoua: "Marrakech-Safi",
  imintanoute: "Marrakech-Safi",

  errachidia: "Drâa-Tafilalet",
  ouarzazate: "Drâa-Tafilalet",
  tinghir: "Drâa-Tafilalet",
  zagora: "Drâa-Tafilalet",
  midelt: "Drâa-Tafilalet",
  "erfoud": "Drâa-Tafilalet",
  "rissani": "Drâa-Tafilalet",

  agadir: "Souss-Massa",
  inezgane: "Souss-Massa",
  taroudant: "Souss-Massa",
  tiznit: "Souss-Massa",
  "chtouka ait baha": "Souss-Massa",
  biougra: "Souss-Massa",
  "ait melloul": "Souss-Massa",
  dcheira: "Souss-Massa",
  "lqliaa": "Souss-Massa",

  guelmim: "Guelmim-Oued Noun",
  "tan-tan": "Guelmim-Oued Noun",
  "sidi ifni": "Guelmim-Oued Noun",
  "assa-zag": "Guelmim-Oued Noun",

  laayoune: "Laâyoune-Sakia El Hamra",
  laâyoune: "Laâyoune-Sakia El Hamra",
  boujdour: "Laâyoune-Sakia El Hamra",
  tarfaya: "Laâyoune-Sakia El Hamra",
  smara: "Laâyoune-Sakia El Hamra",

  dakhla: "Dakhla-Oued Ed-Dahab",
  aousserd: "Dakhla-Oued Ed-Dahab",

  // Communes supplémentaires indexées depuis semsarai.ma
  zenata: "Casablanca-Settat",
  harhoura: "Rabat-Salé-Kénitra",
  "el menzeh": "Rabat-Salé-Kénitra",
  "el-jadida": "Casablanca-Settat",
  benslimane: "Casablanca-Settat",
  errahma: "Casablanca-Settat",
  tamesna: "Rabat-Salé-Kénitra",
  taghazout: "Souss-Massa",
  "m'diq": "Tanger-Tétouan-Al Hoceïma",
  "m-diq-fnideq": "Tanger-Tétouan-Al Hoceïma",
  deroua: "Marrakech-Safi",
  bouknadel: "Rabat-Salé-Kénitra",
  "ben guerir": "Marrakech-Safi",
  mehdia: "Rabat-Salé-Kénitra",
  tassoultante: "Marrakech-Safi",
  aourir: "Souss-Massa",
  "cabo negro": "Tanger-Tétouan-Al Hoceïma",
  "oulad salah": "Casablanca-Settat",
  "tit mellil": "Casablanca-Settat",
  "inezgane-ait-melloul": "Souss-Massa",
  gueznaia: "Tanger-Tétouan-Al Hoceïma",
  "oued laou": "Tanger-Tétouan-Al Hoceïma",
  "moulay bousselham": "Rabat-Salé-Kénitra",
  "oujda-angad": "Oriental",
  zemamra: "Casablanca-Settat",
  selouane: "Oriental",
  azla: "Oriental",
  mirleft: "Guelmim-Oued Noun",
  drargua: "Souss-Massa",
  "ain harrouda": "Casablanca-Settat",
  "aïn harrouda": "Casablanca-Settat",
  "ain attig": "Rabat-Salé-Kénitra",
  "ain aouda": "Rabat-Salé-Kénitra",
  "al bahraoyine": "Rabat-Salé-Kénitra",
  "dcheïra el jihadia": "Souss-Massa",
  "sidi bouzid": "Marrakech-Safi",
  taroudannt: "Souss-Massa",
  "fahs-anjra-": "Tanger-Tétouan-Al Hoceïma",
  "agadir melloul": "Souss-Massa",
  chellalate: "Casablanca-Settat",
  "oulad tayeb": "Fès-Meknès",
  "el-hajeb": "Fès-Meknès",
  inzegan: "Souss-Massa",
  "béni yakhlef": "Casablanca-Settat",
  soualem: "Casablanca-Settat",
  "al-haouz": "Marrakech-Safi",
  "sidi-bennour": "Casablanca-Settat",
  "beni-mellal": "Béni Mellal-Khénifra",
  "tnine aglou": "Souss-Massa",
  "moulay-yacoub": "Fès-Meknès",
  "fquih-ben-salah": "Béni Mellal-Khénifra",
  "moulay abdallah": "Casablanca-Settat",
  "lamharza essahel": "Casablanca-Settat",
  cherrat: "Casablanca-Settat",
  tifelt: "Rabat-Salé-Kénitra",
  haouzia: "Casablanca-Settat",
  rommani: "Rabat-Salé-Kénitra",
  "ait youssef ou ali": "Fès-Meknès",
  "ksar sghir": "Tanger-Tétouan-Al Hoceïma",
  ouislane: "Fès-Meknès",
  "ras el ma": "Tanger-Tétouan-Al Hoceïma",
  "sidi-ifni": "Guelmim-Oued Noun",
  boukhalef: "Tanger-Tétouan-Al Hoceïma",
  taounate: "Fès-Meknès",
  rehamna: "Marrakech-Safi",
  "sidi yahya zaer": "Rabat-Salé-Kénitra",
  "thar es-souk": "Fès-Meknès",
  ourika: "Marrakech-Safi",
  "ouled teïma": "Souss-Massa",
  "sidi hajjaj oued hassar": "Casablanca-Settat",
  "ain beida": "Oriental",
  "bni ansar": "Oriental",
  oualidia: "Casablanca-Settat",
};

const REGION_ALIASES: Record<string, MoroccoRegion> = {
  "grand casablanca": "Casablanca-Settat",
  "casablanca-settat": "Casablanca-Settat",
  "marrakech-safi": "Marrakech-Safi",
  "rabat-sale-kenitra": "Rabat-Salé-Kénitra",
  "rabat-salé-kénitra": "Rabat-Salé-Kénitra",
  "fes-meknes": "Fès-Meknès",
  "fès-meknès": "Fès-Meknès",
  "tanger-tetouan-al hoceima": "Tanger-Tétouan-Al Hoceïma",
  "tanger-tétouan-al hoceïma": "Tanger-Tétouan-Al Hoceïma",
  "souss-massa": "Souss-Massa",
  "draa-tafilalet": "Drâa-Tafilalet",
  "drâa-tafilalet": "Drâa-Tafilalet",
  "beni mellal-khenifra": "Béni Mellal-Khénifra",
  "béni mellal-khénifra": "Béni Mellal-Khénifra",
  "guelmim-oued noun": "Guelmim-Oued Noun",
  "laayoune-sakia el hamra": "Laâyoune-Sakia El Hamra",
  "laâyoune-sakia el hamra": "Laâyoune-Sakia El Hamra",
  "dakhla-oued ed-dahab": "Dakhla-Oued Ed-Dahab",
};

export function resolveMoroccoRegion(city: string, hint?: string): MoroccoRegion | string {
  const cityKey = normalizeKey(city);
  const mapped = CITY_TO_REGION[cityKey];
  if (mapped) return mapped;

  if (hint) {
    const hintKey = normalizeKey(hint);
    const fromHint = REGION_ALIASES[hintKey] ?? CITY_TO_REGION[hintKey];
    if (fromHint) return fromHint;
    if (MOROCCO_REGIONS.some((r) => normalizeKey(r) === hintKey)) {
      return hint;
    }
  }

  return "Autres communes";
}
