/**
 * Import annonces depuis SEMSAR AI (semsarai.ma) via API publique + téléchargement photos.
 *
 * Usage:
 *   pnpm import:semsarai
 *   SEMSARAI_IMPORT_LIMIT=200 pnpm import:semsarai
 *   pnpm import:semsarai -- --no-download
 */
import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import { fetchSemsaraiProperties } from "../src/lib/semsarai/client";
import { semsaraiPropertyToListing, semsaraiSlug } from "../src/lib/semsarai/normalizer";
import { downloadListingImages } from "../src/lib/media/download-images";

const IMPORT_LIMIT = Number(process.env.SEMSARAI_IMPORT_LIMIT ?? "500");
const PAGE_SIZE = Number(process.env.SEMSARAI_PAGE_SIZE ?? "50");
const DOWNLOAD_IMAGES = !process.argv.includes("--no-download");
const MEDIA_ROOT = path.join(process.cwd(), "public");
const MEDIA_PREFIX = "media/semsarai";

async function main() {
  console.info(`[import:semsarai] Import depuis semsarai.ma (limite ${IMPORT_LIMIT})…`);

  const collected = [];
  let page = 1;
  let totalCount = 0;

  while (collected.length < IMPORT_LIMIT) {
    const batch = await fetchSemsaraiProperties({
      page,
      limit: Math.min(PAGE_SIZE, IMPORT_LIMIT - collected.length),
    });
    totalCount = batch.totalCount;
    if (!batch.properties.length) break;
    collected.push(...batch.properties);
    console.info(`[import:semsarai] Page ${page} — ${collected.length}/${IMPORT_LIMIT} (API total ${totalCount})`);
    page += 1;
    if (collected.length >= IMPORT_LIMIT) break;
  }

  const slice = collected.slice(0, IMPORT_LIMIT);

  if (DOWNLOAD_IMAGES) {
    mkdirSync(path.join(MEDIA_ROOT, MEDIA_PREFIX), { recursive: true });
    console.info(`[import:semsarai] Téléchargement photos → public/${MEDIA_PREFIX}/`);
  }

  const listings = [];
  const manifest: Array<{ id: string; slug: string; sourceUrl: string; images: Array<{ sourceUrl: string; publicUrl: string }> }> = [];

  for (const [index, property] of slice.entries()) {
    const slug = semsaraiSlug(property.title, property.id);
    const remoteImages = (property.images ?? []).filter(Boolean);
    let images = remoteImages;

    if (DOWNLOAD_IMAGES && remoteImages.length > 0) {
      const downloaded = await downloadListingImages(remoteImages, {
        mediaRoot: MEDIA_ROOT,
        publicPrefix: MEDIA_PREFIX,
        listingKey: property.id.slice(0, 12),
        concurrency: 4,
      });
      const localBySource = new Map(downloaded.map((d) => [d.sourceUrl.split("?")[0], d.publicUrl]));
      images = remoteImages.map((url) => localBySource.get(url.split("?")[0]) ?? url);
      if (downloaded.length > 0) {
        manifest.push({
          id: property.id,
          slug,
          sourceUrl: property.link ?? `https://www.semsarai.ma/property/${slug}`,
          images: downloaded.map((d) => ({ sourceUrl: d.sourceUrl, publicUrl: d.publicUrl })),
        });
      }
      if ((index + 1) % 10 === 0) {
        console.info(`[import:semsarai] ${index + 1}/${slice.length} annonces traitées`);
      }
    }

    listings.push(semsaraiPropertyToListing(property, images));
  }

  const totalPhotos = listings.reduce((n, l) => n + l.images.length, 0);
  const outPath = path.join(process.cwd(), "src/lib/data/semsarai-listings.ts");
  const content = `/** Auto-generated by scripts/import-semsarai.ts — ${new Date().toISOString()} */
import type { DemoListing } from "@/lib/data/demo-data";

export const SEMSARAI_LISTINGS: DemoListing[] = ${JSON.stringify(listings, null, 2)} as DemoListing[];

export const SEMSARAI_IMPORT_META = {
  source: "SEMSAR AI",
  sourceUrl: "https://www.semsarai.ma",
  apiUrl: "${process.env.SEMSARAI_API_URL ?? "https://server-production-a8d0.up.railway.app"}",
  importedAt: "${new Date().toISOString()}",
  count: ${listings.length},
  apiTotalCount: ${totalCount},
  photosDownloaded: ${DOWNLOAD_IMAGES},
  totalPhotos: ${totalPhotos},
  isAggregated: true,
};
`;

  writeFileSync(outPath, content);

  if (DOWNLOAD_IMAGES && manifest.length > 0) {
    const manifestPath = path.join(process.cwd(), "data/media/semsarai-manifest.json");
    mkdirSync(path.dirname(manifestPath), { recursive: true });
    writeFileSync(manifestPath, JSON.stringify({ importedAt: new Date().toISOString(), listings: manifest }, null, 2));
  }

  console.info(
    `[import:semsarai] Wrote ${listings.length} listings (${totalPhotos} photos) → ${outPath}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
